---
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - ROLE_NAME: ntp
  matrix:
    - MOLECULE_DISTRO: centos:7
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /usr/sbin/init
    - MOLECULE_DISTRO: fedora:27
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /usr/sbin/init
    - MOLECULE_DISTRO: fedora:28
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /usr/sbin/init
    - MOLECULE_DISTRO: ubuntu-upstart:trusty
      MOLECULE_COMMAND: /sbin/init
    - MOLECULE_DISTRO: ubuntu:xenial
      MOLECULE_COMMAND: /sbin/init
    - MOLECULE_DISTRO: ubuntu:bionic
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /lib/systemd/systemd
    - MOLECULE_DISTRO: debian:jessie
      MOLECULE_COMMAND: /sbin/init
    - MOLECULE_DISTRO: debian:stretch
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /lib/systemd/systemd

install:
  - pip install testinfra molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME ericsysmin.$ROLE_NAME
  - cd ericsysmin.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
